name: Publish to Maven Central

on:
  release:
    types: [published,edited]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    
    - name: Build and Test
      run: ./gradlew -Pversion=${{ github.event.release.tag_name }} build

    - name: Publish to Staging Repository
      run: ./gradlew -Pversion=${{ github.event.release.tag_name }} publish

    - name: Deploy to Maven Central
      env:
        JRELEASER_NEXUS2_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        JRELEASER_NEXUS2_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        JRELEASER_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        JRELEASER_GPG_SECRET_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        JRELEASER_GPG_PUBLIC_KEY: ${{ vars.MAVEN_GPG_PUBLIC_KEY }}
      run: ./gradlew -Pversion=${{ github.event.release.tag_name }} jreleaserDeploy